from enum import Enum


class Effect(Enum):
    SPEED = "minecraft:speed"
    SLOWNESS = "minecraft:slowness"
    HASTE = "minecraft:haste"
    MINING_FATIGUE = "minecraft:mining_fatigue"
    STRENGTH = "minecraft:strength"
    INSTANT_HEALTH = "minecraft:instant_health"
    INSTANT_DAMAGE = "minecraft:instant_damage"
    JUMP_BOOST = "minecraft:jump_boost"
    NAUSEA = "minecraft:nausea"
    REGENERATION = "minecraft:regeneration"
    RESISTANCE = "minecraft:resistance"
    FIRE_RESISTANCE = "minecraft:fire_resistance"
    WATER_BREATHING = "minecraft:water_breathing"
    INVISIBILITY = "minecraft:invisibility"
    BLINDNESS = "minecraft:blindness"
    NIGHT_VISION = "minecraft:night_vision"
    HUNGER = "minecraft:hunger"
    WEAKNESS = "minecraft:weakness"
    POISON = "minecraft:poison"
    WITHER = "minecraft:wither"
    HEALTH_BOOST = "minecraft:health_boost"
    ABSORPTION = "minecraft:absorption"
    SATURATION = "minecraft:saturation"
    GLOWING = "minecraft:glowing"
    LUCK = "minecraft:luck"
    UNLUCK = "minecraft:unluck"
    LEVITATION = "minecraft:levitation"
    SLOW_FALLING = "minecraft:slow_falling"
    CONDUIT_POWER = "minecraft:conduit_power"
    DOLPHINS_GRACE = "minecraft:dolphins_grace"
    BAD_OMEN = "minecraft:bad_omen"
    HERO_OF_THE_VILLAGE = "minecraft:hero_of_the_village"
    DARKNESS = "minecraft:darkness"
