name: Release on Pypi
on:
    release:
        types: [published]

jobs:
    ReleasePypi:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10.8"
            - name: Build and publish to pypi
              uses: JRubics/poetry-publish@v1.13
              with:
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
                  python_version: "3.10"
                  allow_poetry_pre_release: "yes"
                  ignore_dev_requirements: "yes"
