on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: "1"
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install and configure Poetry
              uses: snok/install-poetry@v1
            - name: Install dependencies
              run: "poetry install"
            - name: Run script
              id: script
              run: "poetry run python tools/update_specific_types.py"
            - name: Push
              if: ${{ steps.script.outputs.release }} == "true"
              uses: stefanzweifel/git-auto-commit-action@v4
            - name: Create Release
              if: ${{ steps.script.outputs.release }} == "true"
              id: create_release
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.script.outputs.tag }}
                  release_name: Release ${{ github.ref }}
                  body: "Added support for Minecraft ${{ steps.script.outputs.mcver }}"
                  draft: false
                  prerelease: false
